## Wraps the functions which generate subsets of the compactness features

#' Note that this function takes some time to run, especially with larger sets of districts.
#'
#' @param shp A shapefile object produced by "read_shapefiles"
#' @param verbose Default TRUE. Inherited from compactness_wrapper().
#' @return A data frame, n by p, where n is the number of districts in the shapefile, and p is 17 plus the number of columns in the metadata.
#' @export
#' @examples
#' filename = "CnclDist_July2012.shp"
#' shp = read_shapefiles(filename)
#' features = generate_features(shp)


generate_features = function(shp, verbose=TRUE){
  if(class(shp)!="compactnessShapefile"){
    print("Warning: input not generated by read_shapefiles function.")
  }
  if(verbose) print("Generating features...")
  firsts = get_first_features(shp) 
  if(verbose) print("First features generated")
  syms = suppressWarnings(get_symmetry_features(shp))
  colnames(syms) = c("sym_x", "sym_y")
  if(verbose) print("Symmetry features generated")
  corners = get_corners_features(shp) 
  if(verbose) print("Corners features generated")
  #edf = get_edf_features(shp) 
  #if(verbose) print("EDF feature generated")
  bounds = suppressWarnings(get_all_bound_features(shp))
  if(verbose) print("Bounding features generated")
  features = cbind(data.frame(shp[[1]]), firsts, bounds, corners, syms)
  #features = cbind(data.frame(shp[[1]]), firsts, bounds, corners, edf, syms)
  if(verbose) print("All features generated!")
  return(features)
}
